/**
 * Guards the evaluator's field list against the schemas it has to track.
 *
 * Both bugs this file exists to prevent were the same mistake in opposite
 * directions, and both silently degraded moderation rather than failing:
 *
 * - The original evaluator read `externalUrl`, a field on no contribution type.
 *   Every guide fell through to a hardcoded spam rating of 7.
 * - The first version of `LINK_FIELDS` missed `repository`, `demoURL` and
 *   `purchaseUrl`, so starters were evaluated with no links at all.
 *
 * `public/schema.json` is the extracted schema, regenerated by `pnpm build`. It
 * cannot tell a `url` field from a `string` — both are strings once extracted —
 * so the second test uses the field name, and anything intentionally left out
 * is listed in `LINK_FIELDS_EXCLUDED` rather than ignored quietly.
 */
import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'
import { describe, test } from 'node:test'
import {
  LINK_FIELDS,
  LINK_FIELDS_EXCLUDED,
  LINKS_PROJECTION,
} from '../src/contributionEvaluation/questions'

const SCHEMA_PATH = path.join(__dirname, '..', 'public', 'schema.json')

/** Field names the projection reads outside of `links`. */
const CONTENT_FIELDS = ['title', 'description', 'body', 'readme']

type ExtractedType = { name?: string; attributes?: Record<string, unknown> }

/** Attribute names per contribution document type, excluding `.reference` shims. */
function contributionTypes(): Map<string, Set<string>> {
  const extracted = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8')) as ExtractedType[]
  const types = new Map<string, Set<string>>()
  for (const type of extracted) {
    const name = type.name ?? ''
    if (!name.startsWith('contribution.') || name.endsWith('.reference')) continue
    types.set(name, new Set(Object.keys(type.attributes ?? {})))
  }
  return types
}

describe('link fields track the contribution schemas', () => {
  const types = contributionTypes()

  test('public/schema.json contains all five contribution types', () => {
    // If this fails the rest of the file is checking nothing, so assert it
    // rather than letting the other tests pass vacuously.
    assert.equal(types.size, 5, `found ${[...types.keys()].join(', ')}`)
  })

  test('every field the projection reads exists on some contribution type', () => {
    // The `externalUrl` regression: a field referenced but never defined.
    const known = new Set([...types.values()].flatMap((fields) => [...fields]))
    for (const field of [...LINK_FIELDS, ...CONTENT_FIELDS]) {
      assert.ok(known.has(field), `${field} is read by the evaluator but exists on no type`)
    }
  })

  test('every link-shaped field in the schemas is used or explicitly excluded', () => {
    // The starter regression: a field defined but never read.
    const looksLikeLink = /url$|^url$|link$|^repository$|^demo/i
    const accounted = new Set<string>([...LINK_FIELDS, ...LINK_FIELDS_EXCLUDED])
    const missing: string[] = []

    for (const [typeName, fields] of types) {
      for (const field of fields) {
        if (!looksLikeLink.test(field)) continue
        if (accounted.has(field)) continue
        missing.push(`${typeName}.${field}`)
      }
    }

    assert.deepEqual(
      missing,
      [],
      'add these to LINK_FIELDS, or to LINK_FIELDS_EXCLUDED if deliberate',
    )
  })

  test('each contribution type that has links contributes at least one', () => {
    // Starters passed the two tests above while still reaching Jev with an empty
    // links array, because the fields they do have were simply absent from the
    // list. This checks per type rather than in aggregate.
    const expectLinks = [
      'contribution.guide',
      'contribution.showcaseProject',
      'contribution.starter',
      'contribution.tool',
    ]
    for (const typeName of expectLinks) {
      const fields = types.get(typeName)
      assert.ok(fields, `${typeName} missing from schema.json`)
      const used = LINK_FIELDS.filter((field) => fields.has(field))
      assert.ok(used.length > 0, `${typeName} contributes no links to the evaluated state`)
    }
  })

  test('nothing is listed as excluded that no longer exists', () => {
    // Keeps the exclusion list from accumulating names after a schema cleanup.
    const known = new Set([...types.values()].flatMap((fields) => [...fields]))
    for (const field of LINK_FIELDS_EXCLUDED) {
      assert.ok(known.has(field), `${field} is excluded but no longer exists; drop it`)
    }
  })

  test('the shared clause is valid GROQ shape and has no duplicates', () => {
    assert.match(LINKS_PROJECTION, /^"links": \[[^[\]]+\]$/)
    assert.equal(new Set(LINK_FIELDS).size, LINK_FIELDS.length, 'duplicate field in LINK_FIELDS')
  })
})
