import {getTaxonomySchema} from './getTaxonomy';

export default getTaxonomySchema({
  name: 'combination',
  title: 'Taxonomy combination',
  description: 'Used to generate SEO-ready landing pages for a combination of taxonomies',
  emoji: '🧠',
  // Combinations' slugs are auto-generated by the chosen taxonomies
  includeSlug: false,
  extraFields: [
    {
      name: 'taxonomies',
      title: 'Taxonomies combined',
      type: 'array',
      validation: (Rule) => [
        Rule.required().min(2).error('Required field with at least 1 entry'),
        Rule.unique(),
        // Hacky way to define our slug automatically
        // (PS: we could also do this with a PublishAction)
        Rule.custom((references, {document}) => {
          // @TODO: apply slug automatically on changes to the chosen taxonomies
          return true;
        }),
      ],
      of: [
        {
          type: 'reference',
          title: 'Reference to a taxonomy',
          to: [
            {type: 'taxonomy.framework'},
            {type: 'taxonomy.language'},
            {type: 'taxonomy.integrationType'},
            {type: 'taxonomy.integration'},
            {type: 'taxonomy.category'},
            {type: 'taxonomy.solution'},
            {type: 'taxonomy.contributionType'},
          ],
        },
      ],
    },
    {
      name: 'slug',
      title: 'Slug for this combination',
      description: "This is automatically generated, don't worry about it 😉 (NOT YET IMPLEMENTED)",
      type: 'slug',
      // readOnly: true,
      // hidden: true,
    },
  ],
});
